name: Nix CI with Cachix

on:
  push:
  workflow_dispatch:
jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Configure Cachix
      uses: cachix/cachix-action@v16
      with:
        name: nix-workbench
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build Nix derivations
      id: build
      run: >
        paths=$(nix build \
          --print-out-paths \
          --no-accept-flake-config \
          .#gtk-css-lsp .#workbench)
        echo "OUT_PATHS=$paths" >> $GITHUB_OUTPUT

    - name: Cache results
      uses: ./
      with:
        name: cachix-action
        signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
        pathsToPush: "${{ steps.paths.outputs.OUT_PATHS }}"
